version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongo-barbershop
    ports:
      - 27017:27017
    networks:
      - node-network

  authorization-server:
    image: franklineker/barbershop-authorization:v1.0.3
    container_name: authorization-server
    environment:
      - DATA_SOURCE_URL=mongodb
      - DATA_SOURCE_DBNAME=drnavalhabarbershop
      - DATA_SOURCE_PORT=27017
      - ISSUER_URI=http://localhost:8081
      - LOGOUT_URI=http://localhost:8081/logout
      - ANGULAR_URI=http://angular-barbershop:4200
    ports:
      - 8081:8081
    networks:
      - node-network

  resource-server:
    image: franklineker/resource-server:v1.0.1
    container_name: resource-server
    environment:
      - DATA_SOURCE_URL=mongodb
      - DATA_SOURCE_DBNAME=drnavalhabarbershop
      - DATA_SOURCE_PORT=27017
      - ISSUER_URI=http://localhost:8081
      - ANGULAR_URI=http://angular-barbershop:4200
    ports:
      - 9000:9000
    depends_on:
      - authorization-server
    networks:
      - node-network

  angular-barbershop:
    image: franklineker/angular-barbershop-teste:v1.0.0  #franklineker/frontend:v1.0.0
    container_name: angular-barbershop
    ports:
      - 8000:8000
    networks:
      - node-network

networks:
  node-network:
    driver: bridge